apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-api
  ports:
    - protocol: TCP
      port: 80 # The public port
      targetPort: 8000 # The port your FastAPI app is running on