name: Build and Push API and UI to Amazon ECR

on:
  push:
    branches:
      - main
    paths:
      - 'fraud-detection-mlops/app/**'
      - 'fraud-detection-mlops/frontend/**'

jobs:
  build-and-push:
    name: Build Docker Images and Deploy to EKS
    runs-on: ubuntu-latest

    env:
      REPOSITORY: fraud-detection-api
      REGION: ap-south-1  # <--- YOUR REGION, UNCHANGED
      API_TAG: latest
      UI_TAG: ui-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push API Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      working-directory: ./fraud-detection-mlops/app
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$API_TAG .
        docker push $REGISTRY/$REPOSITORY:$API_TAG

    - name: Build and Push UI Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      working-directory: ./fraud-detection-mlops/frontend
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$UI_TAG .
        docker push $REGISTRY/$REPOSITORY:$UI_TAG

    - name: Update Deployment YAMLs with Image Paths
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Replace the placeholders in BOTH files
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|$REGISTRY/$REPOSITORY:$API_TAG|g" fraud-detection-mlops/k8s/deployment.yaml
        sed -i "s|UI_IMAGE_PLACEHOLDER|$REGISTRY/$REPOSITORY:$UI_TAG|g" fraud-detection-mlops/k8s/ui-deployment.yaml

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name fraud-detection-eks --region ${{ env.REGION }}

    - name: Deploy to EKS
      run: |
        # Apply Backend
        kubectl apply -f fraud-detection-mlops/k8s/deployment.yaml
        kubectl apply -f fraud-detection-mlops/k8s/service.yaml
        # Apply Frontend
        kubectl apply -f fraud-detection-mlops/k8s/ui-deployment.yaml