name: Build and Push API and UI

on:
  push:
    branches:
      - main
      - master
  # This adds a manual "Play" button in the Actions tab
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: fraud-detection-api
      REGION: ap-south-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Path Check
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Images
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build API
          docker build -t $REGISTRY/$REPOSITORY:latest ./fraud-detection-mlops/app
          docker push $REGISTRY/$REPOSITORY:latest
          # Build UI
          docker build -t $REGISTRY/$REPOSITORY:ui-latest ./fraud-detection-mlops/frontend
          docker push $REGISTRY/$REPOSITORY:ui-latest

      - name: Deploy
        run: |
          aws eks update-kubeconfig --name fraud-detection-eks --region ${{ env.REGION }}
          
          # Replace placeholders and apply
          sed -i "s|DOCKER_IMAGE_PLACEHOLDER|${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:latest|g" fraud-detection-mlops/k8s/deployment.yaml
          sed -i "s|UI_IMAGE_PLACEHOLDER|${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:ui-latest|g" fraud-detection-mlops/k8s/ui-deployment.yaml
          
          kubectl apply -f fraud-detection-mlops/k8s/